print("Hello World!")
print("I am a computer.")
print("My human overlord is named Wesley.")
print("He is 18 years old.")
print("LightBlue is his favourite color.")
print("Wesley is pleased to make your acquaintance!")
print("Goodbye.")